package com.Lyno.matchmindai.presentation.model

import com.Lyno.matchmindai.domain.model.AgentResponse
import com.Lyno.matchmindai.domain.model.MatchPrediction

/**
 * Represents a message in chat conversation between user and assistant.
 * Follows Clean Architecture principles - this is a presentation layer model.
 */
enum class ChatRole {
    USER,
    ASSISTANT
}

/**
 * Data class representing a single chat message.
 * @param id Unique identifier for message (auto-generated by default)
 * @param role The role of message sender (USER or ASSISTANT)
 * @param text Text content for user messages or error messages
 * @param prediction Match prediction for assistant messages (legacy support)
 * @param agentResponse Flexible agent response for new conversation flow
 * @param timestamp Timestamp when message was created (in milliseconds)
 * @param isHidden Whether this message should be hidden from the UI (e.g., tool outputs)
 */
data class ChatMessage(
    val id: String = java.util.UUID.randomUUID().toString(),
    val role: ChatRole,
    val text: String? = null,
    val prediction: MatchPrediction? = null,
    val agentResponse: AgentResponse? = null,
    val timestamp: Long = System.currentTimeMillis(),
    val isHidden: Boolean = false
) {
    /**
     * Helper function to check if this message has content.
     */
    fun hasContent(): Boolean {
        return text?.isNotEmpty() == true || prediction != null || agentResponse != null
    }
    
    /**
     * Helper function to get display text for this message.
     */
    fun getDisplayText(): String {
        return when {
            agentResponse != null -> agentResponse.text
            text != null -> text
            prediction != null -> prediction.reasoning
            else -> ""
        }
    }
}
